# Generated by Django 5.2.6 on 2026-01-08 23:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0008_alter_animal_options"),
        ("engagements", "0002_alter_animalengagement_options_visit"),
        ("shelters", "0003_shelter_bank_account_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("achievement", "Logro"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Tipo de misión",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("feed", "Alimentar animales"),
                            ("clean", "Limpiar animales"),
                            ("health", "Contribuir a salud"),
                            ("login", "Iniciar sesión"),
                            ("sponsor", "Apadrinar un animal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "target_count",
                    models.IntegerField(default=1, verbose_name="Cantidad objetivo"),
                ),
                (
                    "xp_reward",
                    models.IntegerField(default=10, verbose_name="Recompensa XP"),
                ),
                (
                    "coins_reward",
                    models.IntegerField(
                        default=50, verbose_name="Recompensa en monedas"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🎯", max_length=10, verbose_name="Icono"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Misión",
                "verbose_name_plural": "Misiones",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre del rango"),
                ),
                ("min_xp", models.IntegerField(verbose_name="XP mínimo requerido")),
                (
                    "icon",
                    models.CharField(
                        default="⭐",
                        help_text="Emoji que representa el rango",
                        max_length=10,
                        verbose_name="Icono/emoji",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color para UI (ej: blue, purple, gold)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Rango",
                "verbose_name_plural": "Rangos",
                "ordering": ["order", "min_xp"],
            },
        ),
        migrations.CreateModel(
            name="CareIndicator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "food_level",
                    models.IntegerField(
                        default=100,
                        help_text="0 = Hambriento, 100 = Bien alimentado",
                        verbose_name="Nivel de alimentación (%)",
                    ),
                ),
                (
                    "hygiene_level",
                    models.IntegerField(
                        default=100,
                        help_text="0 = Sucio, 100 = Limpio",
                        verbose_name="Nivel de higiene (%)",
                    ),
                ),
                (
                    "health_level",
                    models.IntegerField(
                        default=100,
                        help_text="0 = Enfermo, 100 = Saludable",
                        verbose_name="Nivel de salud (%)",
                    ),
                ),
                (
                    "last_food_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_hygiene_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_health_update",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "engagement",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="care_indicator",
                        to="engagements.animalengagement",
                        verbose_name="Apadrinamiento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Indicador de Cuidado",
                "verbose_name_plural": "Indicadores de Cuidado",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CareAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[("F", "Feed"), ("H", "Hygiene"), ("M", "Medical")],
                        max_length=1,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "amount_increased",
                    models.IntegerField(
                        help_text="Cuánto subió el indicador",
                        verbose_name="Cantidad aumentada (%)",
                    ),
                ),
                (
                    "coins_spent",
                    models.IntegerField(default=0, verbose_name="Monedas gastadas"),
                ),
                ("xp_earned", models.IntegerField(default=0, verbose_name="XP ganado")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "care_indicator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="gamifications.careindicator",
                        verbose_name="Indicador de cuidado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acción de Cuidado",
                "verbose_name_plural": "Acciones de Cuidado",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DirectPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cop",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto en COP"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pendiente"),
                            ("A", "Aprobado"),
                            ("T", "Transferido"),
                            ("R", "Rechazado"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Referencia de pago",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID de transacción Wompi",
                    ),
                ),
                (
                    "transferred_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de transferencia"
                    ),
                ),
                (
                    "transfer_reference",
                    models.CharField(
                        blank=True,
                        help_text="Referencia del pago al albergue",
                        max_length=255,
                        null=True,
                        verbose_name="Referencia de transferencia",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas del administrador"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "history",
                    models.ForeignKey(
                        help_text="Evento médico al que se contribuye",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_payments",
                        to="animals.history",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_payments",
                        to="shelters.shelter",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago Directo",
                "verbose_name_plural": "Pagos Directos",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(default=0, verbose_name="Saldo de monedas"),
                ),
                (
                    "total_earned",
                    models.IntegerField(
                        default=0, verbose_name="Total ganado (histórico)"
                    ),
                ),
                (
                    "total_spent",
                    models.IntegerField(
                        default=0, verbose_name="Total gastado (histórico)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to="shelters.shelter",
                        verbose_name="Albergue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billetera Virtual",
                "verbose_name_plural": "Billeteras Virtuales",
                "db_table": "wallet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletRecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_cop",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Dinero real donado",
                        max_digits=10,
                        verbose_name="Monto en COP",
                    ),
                ),
                (
                    "coins_received",
                    models.IntegerField(
                        help_text="Monedas virtuales a agregar (1 COP = 0.1 monedas)",
                        verbose_name="Monedas recibidas",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("PSE", "PSE"),
                            ("CARD", "Tarjeta de Crédito/Débito"),
                            ("TRANSFER", "Transferencia Bancaria"),
                            ("CASH", "Efectivo"),
                        ],
                        max_length=10,
                        verbose_name="Método de pago",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("P", "Pending"),
                            ("A", "Approved"),
                            ("R", "Rejected"),
                            ("F", "Failed"),
                        ],
                        default="P",
                        max_length=1,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del banco o pasarela de pago",
                        max_length=255,
                        null=True,
                        verbose_name="ID de transacción externa",
                    ),
                ),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Referencia de pago",
                    ),
                ),
                (
                    "wompi_data",
                    models.JSONField(
                        blank=True,
                        help_text="Datos completos de la respuesta de Wompi",
                        null=True,
                        verbose_name="Datos de Wompi",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="Notas del administrador"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recharges",
                        to="gamifications.wallet",
                        verbose_name="Billetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recarga de Billetera",
                "verbose_name_plural": "Recargas de Billetera",
                "db_table": "wallet_recharge",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("E", "Earn"), ("S", "Spend")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Cantidad")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Descripción"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="gamifications.wallet",
                        verbose_name="Billetera",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transacción de Billetera",
                "verbose_name_plural": "Transacciones de Billetera",
                "db_table": "wallet_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserMissionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(default=0, verbose_name="Progreso actual"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Día para diarias, inicio de semana para semanales",
                        verbose_name="Fecha del periodo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="gamifications.mission",
                        verbose_name="Misión",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Misión",
                "verbose_name_plural": "Progresos de Misiones",
                "ordering": ["-created_at"],
                "unique_together": {("user", "mission", "period_date")},
            },
        ),
        migrations.AddIndex(
            model_name="wallet",
            index=models.Index(
                fields=["user", "shelter"], name="wallet_user_id_144313_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="wallet",
            unique_together={("user", "shelter")},
        ),
    ]
