# Generated by Django 5.2.6 on 2026-01-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mission",
            name="scope",
            field=models.CharField(
                choices=[("shelter", "Refugio específico"), ("global", "Global")],
                default="shelter",
                max_length=20,
                verbose_name="Alcance",
            ),
        ),
    ]
