# Generated by Django 5.2.6 on 2025-11-09 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0002_directpayment_coinusage_monthlydistribution"),
        ("shelters", "0003_shelter_bank_account_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="monthlydistribution",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="monthlydistribution",
            name="shelter",
        ),
        migrations.AddField(
            model_name="wallettransaction",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                help_text="Albergue al que pertenece esta transacción",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="shelters.shelter",
                verbose_name="Albergue",
            ),
        ),
        migrations.CreateModel(
            name="ShelterWalletBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.IntegerField(
                        default=0, verbose_name="Saldo de monedas para este albergue"
                    ),
                ),
                (
                    "total_earned",
                    models.IntegerField(
                        default=0, verbose_name="Total ganado (histórico)"
                    ),
                ),
                (
                    "total_spent",
                    models.IntegerField(
                        default=0, verbose_name="Total gastado (histórico)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_balances",
                        to="shelters.shelter",
                        verbose_name="Albergue",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shelter_balances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Balance por Albergue",
                "verbose_name_plural": "Balances por Albergue",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="CoinUsage",
        ),
        migrations.DeleteModel(
            name="MonthlyDistribution",
        ),
        migrations.AddIndex(
            model_name="shelterwalletbalance",
            index=models.Index(
                fields=["user", "shelter"], name="gamificatio_user_id_912c4a_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shelterwalletbalance",
            unique_together={("user", "shelter")},
        ),
    ]
