# Generated by Django 5.2.6 on 2026-04-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0002_mission_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="walletrecharge",
            name="failure_reason",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Razon del fallo"
            ),
        ),
        migrations.AddField(
            model_name="walletrecharge",
            name="original_recharge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="retries",
                to="gamifications.walletrecharge",
            ),
        ),
        migrations.AddField(
            model_name="walletrecharge",
            name="retry_count",
            field=models.IntegerField(
                default=0, verbose_name="Numero de reintentos realizados"
            ),
        ),
        migrations.AddField(
            model_name="walletrecharge",
            name="retry_key",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Clave de reintento",
            ),
        ),
    ]
