# Generated by Django 5.2.6 on 2025-11-10 06:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gamifications", "0003_alter_monthlydistribution_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "mission_type",
                    models.CharField(
                        choices=[
                            ("daily", "Diaria"),
                            ("weekly", "Semanal"),
                            ("achievement", "Logro"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="Tipo de misión",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("feed", "Alimentar animales"),
                            ("clean", "Limpiar animales"),
                            ("health", "Contribuir a salud"),
                            ("login", "Iniciar sesión"),
                            ("sponsor", "Apadrinar un animal"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de acción",
                    ),
                ),
                (
                    "target_count",
                    models.IntegerField(default=1, verbose_name="Cantidad objetivo"),
                ),
                (
                    "xp_reward",
                    models.IntegerField(default=10, verbose_name="Recompensa XP"),
                ),
                (
                    "coins_reward",
                    models.IntegerField(
                        default=50, verbose_name="Recompensa en monedas"
                    ),
                ),
                (
                    "icon",
                    models.CharField(default="🎯", max_length=10, verbose_name="Icono"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activa")),
                (
                    "order",
                    models.IntegerField(
                        default=0, verbose_name="Orden de visualización"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Misión",
                "verbose_name_plural": "Misiones",
                "ordering": ["order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Nombre del rango"),
                ),
                ("min_xp", models.IntegerField(verbose_name="XP mínimo requerido")),
                (
                    "icon",
                    models.CharField(
                        default="⭐",
                        help_text="Emoji que representa el rango",
                        max_length=10,
                        verbose_name="Icono/emoji",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="gray",
                        help_text="Color para UI (ej: blue, purple, gold)",
                        max_length=20,
                        verbose_name="Color",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Orden")),
            ],
            options={
                "verbose_name": "Rango",
                "verbose_name_plural": "Rangos",
                "ordering": ["order", "min_xp"],
            },
        ),
        migrations.CreateModel(
            name="UserMissionProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_count",
                    models.IntegerField(default=0, verbose_name="Progreso actual"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de completado"
                    ),
                ),
                (
                    "period_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Día para diarias, inicio de semana para semanales",
                        verbose_name="Fecha del periodo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="gamifications.mission",
                        verbose_name="Misión",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mission_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Progreso de Misión",
                "verbose_name_plural": "Progresos de Misiones",
                "ordering": ["-created_at"],
                "unique_together": {("user", "mission", "period_date")},
            },
        ),
    ]
