# Generated by Django 5.2.6 on 2025-11-10 06:04

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_created_at_customuser_experience_points_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="address",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Dirección de domicilio",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="0000000000",
                max_length=128,
                region="CO",
                verbose_name="Teléfono",
            ),
        ),
    ]
