# Generated by Django 5.2.6 on 2026-01-27 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_shelter_bank_account_number_and_more"),
        ("users", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="coins",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Monedas virtuales"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="experience_points",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Puntos de experiencia"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="shelter",
            field=models.ForeignKey(
                blank=True,
                help_text="Solo para Shelter Admins: albergue que gestionan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="shelters.shelter",
                verbose_name="Albergue asignado",
            ),
        ),
    ]
