# Generated by Django 5.2.6 on 2026-02-04 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_customuser_coins_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="accepted_data_policy",
            field=models.BooleanField(
                default=False, verbose_name="Términos y condicones aceptados"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="accepted_data_policy_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de aceptacion de términos",
            ),
            preserve_default=False,
        ),
    ]
