# Generated by Django 5.2.6 on 2026-02-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_accepted_data_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="accepted_data_policy_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de aceptación de términos"
            ),
        ),
    ]
