[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn appfundationwDj.wsgi:application --bind 0.0.0.0:8080"

# Degradar indicadores cada 4 horas
[[crons]]
schedule = "0 */4 * * *"
command = "python manage.py degrade_indicators"

# Resetear misiones diarias a las 5:01 AM
[[crons]]
schedule = "1 5 * * *"
command = "python manage.py reset_missions"