# Generated by Django 5.2.6 on 2025-10-10 04:55

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="availability",
            field=models.CharField(
                choices=[("A", "Adoption"),
                         ("S", "Sponsorship"), ("B", "Both")],
                default="A",
                max_length=1,
                verbose_name="Disponibilidad",
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("V", "Vacunacion"),
                            ("E", "Esterilizacion"),
                            ("C", "Cirugia"),
                            ("I", "Ingreso"),
                            ("O", "Otro"),
                        ],
                        default="I",
                        max_length=1,
                        verbose_name="Tipo de historia",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripcion")),
                (
                    "location_found",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dónde se encontró",
                    ),
                ),
                (
                    "entry_date",
                    models.DateField(
                        default=datetime.date.today, verbose_name="Fecha de historia"
                    ),
                ),
                (
                    "exit_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de salida"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="animals.animal",
                        verbose_name="Animal",
                    ),
                ),
            ],
        ),
    ]
