# Generated by Django 5.2.6 on 2025-11-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0007_alter_history_location_found"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animal",
            options={"verbose_name": "Animalito", "verbose_name_plural": "Animalitos"},
        ),
    ]
