# Generated by Django 5.2.6 on 2026-01-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0008_alter_animal_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="status",
            field=models.CharField(
                choices=[("O", "Huerfano"), ("S", "Apadrinado"), ("A", "Adoptado")],
                default="O",
                max_length=1,
                verbose_name="Estado del animal",
            ),
        ),
    ]
