# Generated by Django 5.2.6 on 2026-02-02 19:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0009_animal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="clinical_document",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Sube la historia clínica en formato PDF, JPG, JPEG, PNG o WEBP",
                max_length=255,
                null=True,
                verbose_name="Documento clínico",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="availability",
            field=models.CharField(
                choices=[("A", "Adopcion"), ("S", "Apadrinamiento"), ("B", "Ambos")],
                default="A",
                max_length=1,
                verbose_name="Disponibilidad",
            ),
        ),
    ]
