# Generated by Django 5.2.6 on 2026-02-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0010_history_clinical_document_alter_animal_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="history",
            name="clinical_document",
            field=models.FileField(
                blank=True,
                help_text="Sube la historia clínica en formato PDF, JPG, JPEG, PNG o WEBP",
                null=True,
                upload_to="clinical_histories/",
                verbose_name="Documento clínico",
            ),
        ),
    ]
