# Generated by Django 5.2.6 on 2025-11-01 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='food_degradation_percentag',
            new_name='food_degradation_percentage',
        ),
    ]
