# Generated by Django 5.2.6 on 2025-11-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shelters",
            "0002_rename_food_degradation_percentag_shelter_food_degradation_percentage",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="bank_account_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Número de cuenta"
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="bank_account_type",
            field=models.CharField(
                blank=True,
                choices=[("SAVINGS", "Ahorros"), ("CHECKING", "Corriente")],
                max_length=20,
                null=True,
                verbose_name="Tipo de cuenta",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="bank_name",
            field=models.CharField(
                blank=True,
                help_text="Bancolombia, Davivienda, etc.",
                max_length=100,
                null=True,
                verbose_name="Nombre del banco",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="identification_number",
            field=models.CharField(
                blank=True,
                help_text="Número de identificación tributaria",
                max_length=50,
                verbose_name="NIT o Cédula",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="legal_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre legal/comercial para transferencias",
                max_length=255,
                verbose_name="Razón social",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="nequi_phone",
            field=models.CharField(
                blank=True,
                help_text="Número Nequi para recibir pagos (ej: 3001234567)",
                max_length=20,
                null=True,
                verbose_name="Teléfono Nequi",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("NEQUI", "Nequi"),
                    ("BANK", "Cuenta Bancaria"),
                    ("WOMPI", "Cuenta Wompi"),
                ],
                default="NEQUI",
                max_length=20,
                verbose_name="Método de pago preferido",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="wompi_merchant_id",
            field=models.CharField(
                blank=True,
                help_text="Si el albergue tiene cuenta Wompi verificada",
                max_length=100,
                null=True,
                verbose_name="Merchant ID de Wompi",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="email",
            field=models.CharField(max_length=255, verbose_name="Email del albergue"),
        ),
    ]
