# Generated by Django 5.2.6 on 2025-09-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Nombre de la raza')),
                ('species', models.CharField(choices=[('C', 'Canino'), ('F', 'Felino')], max_length=1, verbose_name='Especie')),
            ],
        ),
    ]
