# Generated by Django 5.2.6 on 2025-11-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("breeds", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="breed",
            options={"verbose_name": "Raza", "verbose_name_plural": "Razas"},
        ),
    ]
