"""
Django settings for appfundationwDj project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import cloudinary
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!

ENVIRONMENT = os.environ.get("ENVIRONMENT", default="local")

DEBUG = ENVIRONMENT == "local"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".railway.app",
    "solidaridad-cucuta.com",
    "www.solidaridad-cucuta.com",
    "proresignation-listlessly-hermina.ngrok-free.dev",
]

# CSRF Configuration
CSRF_TRUSTED_ORIGINS = [
    "https://solidaridad-cucuta.com",
    "https://www.solidaridad-cucuta.com",
    "https://*.railway.app",
    "https://proresignation-listlessly-hermina.ngrok-free.dev",
]

# Cookie Settings
SESSION_COOKIE_SECURE = ENVIRONMENT != "local"
CSRF_COOKIE_SECURE = ENVIRONMENT != "local"
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# CORS Configuration
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True


if ENVIRONMENT == "local":
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True") == "True"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "corsheaders",
    "crispy_forms",
    "crispy_tailwind",
    "cloudinary",
    "cloudinary_storage",
    "phonenumber_field",
    "shelters",
    "silk",
    "users",
    "breeds",
    "animals",
    "engagements",
    "gamifications",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "silk.middleware.SilkyMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "appfundationwDj.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "appfundationwDj.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if ENVIRONMENT == "local":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    database_url = os.environ.get("DATABASE_URL")

    if database_url:
        import dj_database_url

        DATABASES = {
            "default": dj_database_url.config(
                default=database_url,
                conn_max_age=600,
            )
        }
    else:
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": os.environ.get("DB_NAME"),
                "USER": os.environ.get("DB_USER"),
                "PASSWORD": os.environ.get("DB_PASSWORD"),
                "HOST": os.environ.get("DB_HOST"),
                "PORT": os.environ.get("DB_PORT", default="5432"),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-co"

TIME_ZONE = "America/Bogota"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Whitenoise Storage Configuration
if ENVIRONMENT == "local":
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.CustomUser"

CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

cloudinary.config(
    cloud_name=os.getenv("CLOUD_NAME"),
    api_key=os.getenv("CLOUD_API_KEY"),
    api_secret=os.getenv("CLOUD_API_SECRET"),
)


DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"

LOGIN_REDIRECT_URL = "/users/home/"

LOGOUT_REDIRECT_URL = "/users/home/"

# Wompi Payment Gateway Configuration
WOMPI_PUBLIC_KEY = os.getenv("WOMPI_PUBLIC_KEY")
WOMPI_PRIVATE_KEY = os.getenv("WOMPI_PRIVATE_KEY")
WOMPI_EVENT_SECRET = os.getenv("WOMPI_EVENT_SECRET")
WOMPI_INTEGRITY_SECRET = os.getenv("WOMPI_INTEGRITY_SECRET")

FUNDATION_APP = "Solidaridad Cúcuta"
WELCOME_TO = "Bienvenidos a"

JAZZMIN_SETTINGS = {
    "site_title": FUNDATION_APP,
    "site_header": FUNDATION_APP,
    "site_brand": FUNDATION_APP,
    "welcome_sign": f"{WELCOME_TO} {FUNDATION_APP}",
    "site_logo": "images/logo.png",
    "site_logo_classes": "img-circle",
    "login_logo": "images/logo.png",
    "login_logo_classes": "img-circle",
    "site_icon": "images/logo.png",
    "custom_css": "css/custom_admin.css",
    "use_nav_sidebar": False,
    "icons": {
        # Auth
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.group": "fas fa-users",
        # Users
        "users.customuser": "fas fa-user-circle",
        # Animals
        "animals.animal": "fas fa-paw",
        "animals.history": "fas fa-history",
        # Breeds
        "breeds.breed": "fas fa-dog",
        # Shelters
        "shelters.shelter": "fas fa-home",
        # Engagements
        "engagements.animalengagement": "fas fa-handshake",
        "engagements.visit": "fas fa-eye",
        # Gamifications
        "gamifications.careindicator": "fas fa-bullseye",
        "gamifications.careaction": "fas fa-check",
        "gamifications.virtualwallet": "fas fa-wallet",
        "gamifications.shelterwalletbalance": "fas fa-donate",
        "gamifications.wallettransaction": "fas fa-exchange-alt",
        "gamifications.walletrecharge": "fas fa-plus-circle",
        "gamifications.directpayment": "fas fa-money-bill-wave",
        "gamifications.rank": "fas fa-trophy",
        "gamifications.mission": "fas fa-flag-checkered",
        "gamifications.usermissionprogress": "fas fa-tasks",
    },
    "side_menu": [
        {
            "label": "Usuarios y Administración",
            "icon": "fas fa-users",
            "models": [
                "users.customuser",
                "auth.user",
                "auth.group",
            ],
        },
        {
            "label": "Gestión de Animales",
            "icon": "fas fa-paw",
            "models": [
                "animals.animal",
                "animals.history",
                "breeds.breed",
                "shelters.shelter",
            ],
        },
        {
            "label": "Interacciones",
            "icon": "fas fa-handshake",
            "models": [
                "engagements.animalengagement",
                "engagements.visit",
            ],
        },
        {
            "label": "Gamificación y Recompensas",
            "icon": "fas fa-star",
            "models": [
                "gamifications.careindicator",
                "gamifications.careaction",
                "gamifications.virtualwallet",
                "gamifications.wallettransaction",
                "gamifications.walletrecharge",
                "gamifications.directpayment",
                "gamifications.shelterwalletbalance",
                "gamifications.rank",
                "gamifications.mission",
                "gamifications.usermissionprogress",
            ],
        },
    ],
    "navigation_expanded": True,
}

SILKY_PYTHON_PROFILER = True
SILKY_PYTHON_PROFILER_BINARY = True
SILKY_MAX_REQUEST_BODY_SIZE = -1  # Sin límite
SILKY_MAX_RESPONSE_BODY_SIZE = -1
SILKY_INTERCEPT_PERCENT = 100  # Registrar 100% de peticiones
SILKY_MAX_RECORDED_REQUESTS = 10000
SILKY_META = True
