# Generated by Django 5.2.6 on 2025-11-16 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="animalengagement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Gestión de Adopcion - Apadrinamiento",
                "verbose_name_plural": "Gestión de Adopciones - Apadrinamientos",
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_date",
                    models.DateTimeField(
                        help_text="Fecha y hora programada para la visita"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Notas u observaciones de la visita",
                        null=True,
                    ),
                ),
                (
                    "evaluation",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Muy Mala"),
                            (2, "Mala"),
                            (3, "Regular"),
                            (4, "Buena"),
                            (5, "Excelente"),
                        ],
                        help_text="Evaluación del estado del animal (1-5). Se completa después de la visita.",
                        null=True,
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(
                        default=False, help_text="Indica si la visita ya fue realizada"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "animal_engagement",
                    models.ForeignKey(
                        help_text="Adopción a la que pertenece esta visita",
                        limit_choices_to={"engagements_type": "A", "status": "A"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="engagements.animalengagement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Visita",
                "verbose_name_plural": "Visitas",
                "ordering": ["-visit_date"],
            },
        ),
    ]
