# Generated by Django 5.2.6 on 2026-01-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0002_alter_animalengagement_options_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalengagement",
            name="pdf_file",
            field=models.URLField(
                blank=True,
                help_text="URL del PDF en Cloudinary",
                max_length=500,
                null=True,
            ),
        ),
    ]
