# Generated by Django 5.2.6 on 2026-01-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0004_alter_animalengagement_pdf_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animalengagement",
            name="pdf_file",
        ),
    ]
