# Generated by Django 5.2.6 on 2026-02-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engagements", "0005_remove_animalengagement_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animalengagement",
            name="engagements_type",
            field=models.CharField(
                choices=[("A", "Adopcion"), ("S", "Apadrinamiento"), ("D", "Donacion")],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="animalengagement",
            name="status",
            field=models.CharField(
                choices=[("P", "Pendiente"), ("A", "Aprobada"), ("R", "Rechazada")],
                default="P",
                max_length=1,
            ),
        ),
    ]
